### ISSUE TITLE
有的设备访问之后还得先选线路，不是直接展示用户名，这种如何显示username

### ISSUE THREAD

**Issue by mrwpro** [adeljck/QAX_VPN_Crack#1]
![image](https://github.com/adeljck/QAX_VPN_Crack/assets/90690030/7ef362c8-775a-4a9c-94b2-91789a2269e1)
虽然读出来了有多少列，但是显示不出来

**Comment by adeljck** [comment]
显示用户的函数写在更改密码里面，也就是说你只有使用-e更改密码参数才会显示具体的用户信息，检测模式只会显示有多少用户。具体代码看module->vpn.go里的Run函数
