### ISSUE TITLE
存在敏感信息 已涉及侵权/违法,请删除 # #1

### ISSUE THREAD

**Issue by QSec-Team** [adeljck/QAX_VPN_Crack#3]
你好，该仓库内容已涉及侵权，请自查并进行清理
1，违法
该文章违反《中华人民共和国网络安全法》第二十六条规定，开展网络安全认证、检测、风险评估等活动，向社会发布系统漏洞、计算机病毒、网络攻击、网络侵入等网络安全信息，应当遵守国家有关规定。《中华人民共和国网络安全法》链接：http://www.cac.gov.cn/2016-11/07/c_1119867116_2.htm

违反《网络产品安全漏洞管理规定》第九条:漏洞发布应与网络安全产品提供者共同协商，并向工信部、公安部报告，不得在网络产品提供者提供网络产品安全漏洞修补措施之前发布漏洞信息；认为有必要提前发布的，应当与相关网络产品提供者共同评估协商，并向工业和信息化部、公安部报告，由工业和信息化部、公安部组织评估后进行发布。https://www.gov.cn/zhengce/zhengceku/2021-07/14/content_5624965.htm
现在要求立即删除我司负面消息。我司保留起诉、索赔等维护自身合法权益的一切权利。

2，侵权
未经我司授权，违规发布并关联我司产品安全漏洞文章信息，此信息的公布侵害了我司的名誉、对我司生产经营造成负面影响、对我司的产品形象造成极其恶劣影响。现在要求对方立即删除我司负面消息。我司保留起诉、索赔等维护自身合法权益的权利。

**Comment by tonyscy** [comment]
66666666666666666

**Comment by No-Github** [comment]
66666666666666666

**Comment by Cl-arctos** [comment]
66666666666666666

**Comment by kemomi** [comment]
6666666，GitHub不归共管吧
